### ISSUE TITLE
Search filters does not work when options are collapsed

### ISSUE THREAD

**Issue by dvolkering** [EmicoEcommerce/Magento2TweakwiseHyva#41]
Hi,
The search filter does not work on all filter options when the filter is collapsed down to +/- 5 results (it is only searching through the 5 options). In my opinion, the functionality from the search filter does not add any value if it is not searching through all the filter options.

Example:
![image](https://github.com/EmicoEcommerce/Magento2TweakwiseHyva/assets/10158097/23cf6fc1-c85d-4216-b150-b06116193c35)

Search for for example "Claas", you won´t find any results. But, if you click the "Meer tonen" button, and search for "Claas" you will get a result. 
![image](https://github.com/EmicoEcommerce/Magento2TweakwiseHyva/assets/10158097/6ab0a828-554d-4637-a1b3-d33a3e45510b)

Example URL:
https://www.misteragri.com/tractor-and-voertuig/verf-49/verf-per-merk

If there are any further questions, please let me know.

**Comment by ahuininga-orisha** [comment]
@dvolkering It should search all available options, not just the visible options. This sounds like an bug. I'll look into this. Thanks for reporting this issue.
